import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/app/Header";
import Footer from "@/app/Footer";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Head>
          <title>Young and Muggleton</title>
          <meta
            name="description"
            content="Experienced Solicitors Servicing Sydney's Inner West &amp;
            Surrounds"
          />
          <meta property="og:title" content="Young and Muggleton" key="title" />
        </Head>
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
